export const APP_SETTINGS = "APP_SETTINGS";
export const APP_SETTINGS_SUCCESS = "APP_SETTINGS_SUCCESS";
export const APP_SETTINGS_FAILURE = "APP_SETTINGS_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const SOCIAL_LOGIN = "SOCIAL_LOGIN";
export const SOCIAL_LOGIN_SUCCESS = "SOCIAL_LOGIN_SUCCESS";
export const SOCIAL_LOGIN_FAILURE = "SOCIAL_LOGIN_FAILURE";

export const LOGOUT = "LOGOUT"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const CLEAR_DATA = "CLEAR_DATA"
export const LOADER = "LOADER"

export const SIGNUP = "SIGNUP";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAILURE = "VERIFY_OTP_FAILURE";

export const VERIFY_LOGIN_OTP = "VERIFY_LOGIN_OTP";
export const VERIFY_LOGIN_OTP_SUCCESS = "VERIFY_LOGIN_OTP_SUCCESS";
export const VERIFY_LOGIN_OTP_FAILURE = "VERIFY_LOGIN_OTP_FAILURE";

export const VERIFY_MOBILE_OTP = "VERIFY_MOBILE_OTP";
export const VERIFY_MOBILE_OTP_SUCCESS = "VERIFY_MOBILE_OTP_SUCCESS";
export const VERIFY_MOBILE_OTP_FAILURE = "VERIFY_MOBILE_OTP_FAILURE";

export const MOBILE_NUM_FIRST_STEP = "MOBILE_NUM_FIRST_STEP";
export const MOBILE_NUM_FIRST_STEP_SUCCESS = "MOBILE_NUM_FIRST_STEP_SUCCESS";
export const MOBILE_NUM_FIRST_STEP_FAILURE = "MOBILE_NUM_FIRST_STEP_FAILURE";

export const MOBILE_NUM_SECOND_STEP = "MOBILE_NUM_SECOND_STEP";
export const MOBILE_NUM_SECOND_STEP_SUCCESS = "MOBILE_NUM_SECOND_STEP_SUCCESS";
export const MOBILE_NUM_SECOND_STEP_FAILURE = "MOBILE_NUM_SECOND_STEP_FAILURE";

export const RESET_PIN_OTP = "RESET_PIN_OTP";
export const RESET_PIN_OTP_SUCCESS = "RESET_PIN_OTP_SUCCESS";
export const RESET_PIN_OTP_FAILURE = "RESET_PIN_OTP_FAILURE";

export const RESET_PIN = "RESET_PIN";
export const RESET_PIN_SUCCESS = "RESET_PIN_SUCCESS";
export const RESET_PIN_FAILURE = "RESET_PIN_FAILURE";

export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const CHANGE_PROFILE_SUCCESS = "CHANGE_PROFILE_SUCCESS";
export const CHANGE_PROFILE_FAILURE = "CHANGE_PROFILE_FAILURE";

export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

export const CONTACT_US = "CONTACT_US";
export const CONTACT_US_SUCCESS = "CONTACT_US_SUCCESS";
export const CONTACT_US_FAILURE = "CONTACT_US_FAILURE";

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_LANGUAGES = "GET_LANGUAGES";
export const GET_LANGUAGES_SUCCESS = "GET_LANGUAGES_SUCCESS";
export const GET_LANGUAGES_FAILURE = "GET_LANGUAGES_FAILURE";

export const EMAIL_UPDATE = "EMAIL_UPDATE";
export const EMAIL_UPDATE_SUCCESS = "EMAIL_UPDATE_SUCCESS";
export const EMAIL_UPDATE_FAILURE = "EMAIL_UPDATE_FAILURE";

export const PHONE_UPDATE = "PHONE_UPDATE";
export const PHONE_UPDATE_SUCCESS = "PHONE_UPDATE_SUCCESS";
export const PHONE_UPDATE_FAILURE = "PHONE_UPDATE_FAILURE";

export const PASSPORT_UPDATE = "PASSPORT_UPDATE";
export const PASSPORT_UPDATE_SUCCESS = "PASSPORT_UPDATE_SUCCESS";
export const PASSPORT_UPDATE_FAILURE = "PASSPORT_UPDATE_FAILURE";

export const EMAIL_UPDATE_OTP = "EMAIL_UPDATE_OTP";
export const EMAIL_UPDATE_OTP_SUCCESS = "EMAIL_UPDATE_OTP_SUCCESS";
export const EMAIL_UPDATE_OTP_FAILURE = "EMAIL_UPDATE_OTP_FAILURE";

export const PHONE_UPDATE_OTP = "PHONE_UPDATE_OTP";
export const PHONE_UPDATE_OTP_SUCCESS = "PHONE_UPDATE_OTP_SUCCESS";
export const PHONE_UPDATE_OTP_FAILURE = "PHONE_UPDATE_OTP_FAILURE";

export const PASSPORT_UPDATE_OTP = "PASSPORT_UPDATE_OTP";
export const PASSPORT_UPDATE_OTP_SUCCESS = "PASSPORT_UPDATE_OTP_SUCCESS";
export const PASSPORT_UPDATE_OTP_FAILURE = "PASSPORT_UPDATE_OTP_FAILURE";

export const SKILLS_UPDATE = "SKILLS_UPDATE";
export const SKILLS_UPDATE_SUCCESS = "SKILLS_UPDATE_SUCCESS";
export const SKILLS_UPDATE_FAILURE = "SKILLS_UPDATE_FAILURE";

export const NOTIFY_PROBLEM_ALERT = "NOTIFY_PROBLEM_ALERT";
export const NOTIFY_PROBLEM_ALERT_SUCCESS = "NOTIFY_PROBLEM_ALERT_SUCCESS";
export const NOTIFY_PROBLEM_ALERT_FAILURE = "NOTIFY_PROBLEM_ALERT_FAILURE";

export const GET_PROBLEM_ALERT = "GET_PROBLEM_ALERT";
export const GET_PROBLEM_ALERT_SUCCESS = "GET_PROBLEM_ALERT_SUCCESS";
export const GET_PROBLEM_ALERT_FAILURE = "GET_PROBLEM_ALERT_FAILURE";

export const ADD_PROBLEM_ALERT = "ADD_PROBLEM_ALERT";
export const ADD_PROBLEM_ALERT_SUCCESS = "ADD_PROBLEM_ALERT_SUCCESS";
export const ADD_PROBLEM_ALERT_FAILURE = "ADD_PROBLEM_ALERT_FAILURE";

export const DELETE_PROBLEM_ALERT = "DELETE_PROBLEM_ALERT";
export const DELETE_PROBLEM_ALERT_SUCCESS = "DELETE_PROBLEM_ALERT_SUCCESS";
export const DELETE_PROBLEM_ALERT_FAILURE = "DELETE_PROBLEM_ALERT_FAILURE";

export const CREATE_JOB = "CREATE_JOB";
export const CREATE_JOB_SUCCESS = "CREATE_JOB_SUCCESS";
export const CREATE_JOB_FAILURE = "CREATE_JOB_FAILURE";

export const EDIT_JOB = "EDIT_JOB";
export const EDIT_JOB_SUCCESS = "EDIT_JOB_SUCCESS";
export const EDIT_JOB_FAILURE = "EDIT_JOB_FAILURE";

export const DELETE_JOB = "DELETE_JOB";
export const DELETE_JOB_SUCCESS = "DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAILURE = "DELETE_JOB_FAILURE";

export const CANCEL_JOB = "CANCEL_JOB";
export const CANCEL_JOB_SUCCESS = "CANCEL_JOB_SUCCESS";
export const CANCEL_JOB_FAILURE = "CANCEL_JOB_FAILURE";

export const GET_JOB = "GET_JOB";
export const GET_JOB_SUCCESS = "GET_JOB_SUCCESS";
export const GET_JOB_FAILURE = "GET_JOB_FAILURE";

export const GET_CLIENT_LIST = "GET_CLIENT_LIST";
export const GET_CLIENT_LIST_SUCCESS = "GET_CLIENT_LIST_SUCCESS";
export const GET_CLIENT_LIST_FAILURE = "GET_CLIENT_LIST_FAILURE";

export const GET_SOLVER_LIST = "GET_SOLVER_LIST";
export const GET_SOLVER_LIST_SUCCESS = "GET_SOLVER_LIST_SUCCESS";
export const GET_SOLVER_LIST_FAILURE = "GET_SOLVER_LIST_FAILURE";

export const ADD_PORTFOLIO_IMAGE = "ADD_PORTFOLIO_IMAGE";
export const ADD_PORTFOLIO_IMAGE_SUCCESS = "ADD_PORTFOLIO_IMAGE_SUCCESS";
export const ADD_PORTFOLIO_IMAGE_FAILURE = "ADD_PORTFOLIO_IMAGE_FAILURE";

export const GET_PORTFOLIO_IMAGES = "GET_PORTFOLIO_IMAGES";
export const GET_PORTFOLIO_IMAGES_SUCCESS = "GET_PORTFOLIO_IMAGES_SUCCESS";
export const GET_PORTFOLIO_IMAGES_FAILURE = "GET_PORTFOLIO_IMAGES_FAILURE";

export const DELETE_PORTFOLIO_IMAGE = "DELETE_PORTFOLIO_IMAGE";
export const DELETE_PORTFOLIO_IMAGE_SUCCESS = "DELETE_PORTFOLIO_IMAGE_SUCCESS";
export const DELETE_PORTFOLIO_IMAGE_FAILURE = "DELETE_PORTFOLIO_IMAGE_FAILURE";

export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILURE = "GET_USER_PROFILE_FAILURE";

export const GET_OTHER_USER_PROFILE = "GET_OTHER_USER_PROFILE";
export const GET_OTHER_USER_PROFILE_SUCCESS = "GET_OTHER_USER_PROFILE_SUCCESS";
export const GET_OTHER_USER_PROFILE_FAILURE = "GET_OTHER_USER_PROFILE_FAILURE";

export const JOB_OFFER_ADD = "JOB_OFFER_ADD";
export const JOB_OFFER_ADD_SUCCESS = "JOB_OFFER_ADD_SUCCESS";
export const JOB_OFFER_ADD_FAILURE = "JOB_OFFER_ADD_FAILURE";

export const JOB_OFFER_EDIT = "JOB_OFFER_EDIT";
export const JOB_OFFER_EDIT_SUCCESS = "JOB_OFFER_EDIT_SUCCESS";
export const JOB_OFFER_EDIT_FAILURE = "JOB_OFFER_EDIT_FAILURE";

export const GET_JOB_OFFER_LIST = "GET_JOB_OFFER_LIST";
export const GET_JOB_OFFER_LIST_SUCCESS = "GET_JOB_OFFER_LIST_SUCCESS";
export const GET_JOB_OFFER_LIST_FAILURE = "GET_JOB_OFFER_LIST_FAILURE";

export const GET_JOB_OFFER = "GET_JOB_OFFER";
export const GET_JOB_OFFER_SUCCESS = "GET_JOB_OFFER_SUCCESS";
export const GET_JOB_OFFER_FAILURE = "GET_JOB_OFFER_FAILURE";

export const JOB_OFFER_ACCEPT = "JOB_OFFER_ACCEPT";
export const JOB_OFFER_ACCEPT_SUCCESS = "JOB_OFFER_ACCEPT_SUCCESS";
export const JOB_OFFER_ACCEPT_FAILURE = "JOB_OFFER_ACCEPT_FAILURE";

export const JOB_OFFER_CANCEL = "JOB_OFFER_CANCEL";
export const JOB_OFFER_CANCEL_SUCCESS = "JOB_OFFER_CANCEL_SUCCESS";
export const JOB_OFFER_CANCEL_FAILURE = "JOB_OFFER_CANCEL_FAILURE";

export const JOB_SOLVED = "JOB_SOLVED";
export const JOB_SOLVED_SUCCESS = "JOB_SOLVED_SUCCESS";
export const JOB_SOLVED_FAILURE = "JOB_SOLVED_FAILURE";

export const JOB_INVITED = "JOB_INVITED";
export const JOB_INVITED_SUCCESS = "JOB_INVITED_SUCCESS";
export const JOB_INVITED_FAILURE = "JOB_INVITED_FAILURE";

export const JOB_QUESTION_ADD = "JOB_QUESTION_ADD";
export const JOB_QUESTION_ADD_SUCCESS = "JOB_QUESTION_ADD_SUCCESS";
export const JOB_QUESTION_ADD_FAILURE = "JOB_QUESTION_ADD_FAILURE";

export const JOB_QUESTION_LIST = "JOB_QUESTION_LIST";
export const JOB_QUESTION_LIST_SUCCESS = "JOB_QUESTION_LIST_SUCCESS";
export const JOB_QUESTION_LIST_FAILURE = "JOB_QUESTION_LIST_FAILURE";

export const JOB_BOOKMARK = "JOB_BOOKMARK";
export const JOB_BOOKMARK_SUCCESS = "JOB_BOOKMARK_SUCCESS";
export const JOB_BOOKMARK_FAILURE = "JOB_BOOKMARK_FAILURE";

export const ADD_REVIEW = "ADD_REVIEW";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS"
export const ADD_REVIEW_FAILURE = "ADD_REVIEW_FAILURE"

export const GET_REVIEW = "GET_REVIEW";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS"
export const GET_REVIEW_FAILURE = "GET_REVIEW_FAILURE"

export const GET_SOLVER_REVIEW = "GET_SOLVER_REVIEW";
export const GET_SOLVER_REVIEW_SUCCESS = "GET_SOLVER_REVIEW_SUCCESS"
export const GET_SOLVER_REVIEW_FAILURE = "GET_SOLVER_REVIEW_FAILURE"

export const ADD_SUPPORT = "ADD_SUPPORT";
export const ADD_SUPPORT_SUCCESS = "ADD_SUPPORT_SUCCESS"
export const ADD_SUPPORT_FAILURE = "ADD_SUPPORT_FAILURE"

export const CLOSE_SUPPORT = "CLOSE_SUPPORT";
export const CLOSE_SUPPORT_SUCCESS = "CLOSE_SUPPORT_SUCCESS"
export const CLOSE_SUPPORT_FAILURE = "CLOSE_SUPPORT_FAILURE"

export const GET_SUPPORT_LIST = "GET_SUPPORT_LIST";
export const GET_SUPPORT_LIST_SUCCESS = "GET_SUPPORT_LIST_SUCCESS"
export const GET_SUPPORT_LIST_FAILURE = "GET_SUPPORT_LIST_FAILURE"

export const SUPPORT_CHAT_LIST = "SUPPORT_CHAT_LIST";
export const SUPPORT_CHAT_LIST_SUCCESS = "SUPPORT_CHAT_LIST_SUCCESS"
export const SUPPORT_CHAT_LIST_FAILURE = "SUPPORT_CHAT_LIST_FAILURE"

export const EDIT_USER_ADDRESS = "EDIT_USER_ADDRESS";
export const EDIT_USER_ADDRESS_SUCCESS = "EDIT_USER_ADDRESS_SUCCESS"
export const EDIT_USER_ADDRESS_FAILURE = "EDIT_USER_ADDRESS_FAILURE"

export const EDIT_SPOKEN_LANGUAGES = "EDIT_SPOKEN_LANGUAGES";
export const EDIT_SPOKEN_LANGUAGES_SUCCESS = "EDIT_SPOKEN_LANGUAGES_SUCCESS"
export const EDIT_SPOKEN_LANGUAGES_FAILURE = "EDIT_SPOKEN_LANGUAGES_FAILURE"



